title: 'Scott Cole'
description: 'personal webpage'

name: 'Scott Cole'
url: https://srcole.github.io

theme: jekyll-theme-cayman

# Google analytics services
google_analytics: UA-81645509-1

#
twitter_username:     scottrcole
github_username:      srcole