# Site settings
title: Scott Cole blog
email: 
description: ""
baseurl: ""
url: "http://srcole.github.io"
twitter_username: scottrcole
github_username:  srcole

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
